pipeline {
    agent any

    environment {
        APP_DIR = 'home/ubuntu/project/backend'
        APP_PORT = '5000'
        VENV_DIR = 'home/ubuntu/project/backend/.venv'
        PM2_APP_NAME = 'flask-backend'
    }

    stages {
        stage('Pull Latest Code') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        echo ">>>Pulling latest code from Github..."
                        git pull origin main
                    '''
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("${WORKSPACE}/backend") {
                    sh '''
                        echo ">>> Setting up virtual environment..."
                        python3 -m venv ${VENV_DIR}
        
                        echo ">>> Installing dependencies..."
                        ${VENV_DIR}/bin/pip install --upgrade pip
                        ${VENV_DIR}/bin/pip install -r requirements.txt
                    '''
                }
            }
        }

        stage("Run Teats") {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        echo ">>> Running tests..."
                        ${VENV_DIR}/bin/pip install pytest --quiet
                        ${VENV_DIR}/bin/pytest tests/ -v || true
                    '''
                }
            }
        }

        stage('Restart Application') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        echo ">>> Restarting Flask app with PM2..."

                        PM2=/home/ubuntu/.nvm/versions/node/v24.14.1/bin/pm2
 
                        if pm2 describe ${PM2_APP_NAME} > /dev/null 2>&1; then
                            echo "App found in PM2 — restarting..."
                            pm2 restart ${PM2_APP_NAME}
                        else
                            echo "App not in PM2 — starting fresh..."
                            pm2 start ${VENV_DIR}/bin/python \
                                --name ${PM2_APP_NAME} \
                                -- app.py
                            pm2 save
                        fi
 
                        pm2 status
                    '''
                }
            }
        }
    }
}
